// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8qUiKil4jXbTM8MM9VPHkw-NY1OCrSvM',
    appId: '1:107549955174:web:b907f8b241ef6e837a09a7',
    messagingSenderId: '107549955174',
    projectId: 'student-manage-67be5',
    authDomain: 'student-manage-67be5.firebaseapp.com',
    storageBucket: 'student-manage-67be5.firebasestorage.app',
    measurementId: 'G-JNLQZM28TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFzSna82v1sNhNIp9CZ-vd1sp6_QoRQnU',
    appId: '1:107549955174:android:fa96c6bf4c40a77c7a09a7',
    messagingSenderId: '107549955174',
    projectId: 'student-manage-67be5',
    storageBucket: 'student-manage-67be5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCFhusFBK73wtdr2QVZJygchjgpuMK60',
    appId: '1:107549955174:ios:33ea58a381b82beb7a09a7',
    messagingSenderId: '107549955174',
    projectId: 'student-manage-67be5',
    storageBucket: 'student-manage-67be5.firebasestorage.app',
    iosBundleId: 'com.example.application1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCFhusFBK73wtdr2QVZJygchjgpuMK60',
    appId: '1:107549955174:ios:33ea58a381b82beb7a09a7',
    messagingSenderId: '107549955174',
    projectId: 'student-manage-67be5',
    storageBucket: 'student-manage-67be5.firebasestorage.app',
    iosBundleId: 'com.example.application1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8qUiKil4jXbTM8MM9VPHkw-NY1OCrSvM',
    appId: '1:107549955174:web:5bcaca599b458b787a09a7',
    messagingSenderId: '107549955174',
    projectId: 'student-manage-67be5',
    authDomain: 'student-manage-67be5.firebaseapp.com',
    storageBucket: 'student-manage-67be5.firebasestorage.app',
    measurementId: 'G-WK1WE50T91',
  );
}
